### ISSUE TITLE
Unable to resolve module react-native-otp-inputs in latest 2.0.1

### ISSUE THREAD

**Issue by Abhishekgarg727** [dsznajder/react-native-otp-inputs#20] opened 2019-04-25 08:13 UTC
When uses version 1 it works fine but latest version 2.0.1 have following problem.

While trying to resolve module `react-native-otp-inputs` 

from file 

`F:\abc\app\components\EmailOTPVerification.js`, 

the package
 `F:\abc\node_modules\react-native-otp-inputs\package.json` was successfully found. 

However, this package itself specifies a `main` module field that could not be resolved 

(`F:\abc\node_modules\react-native-otp-inputs\lib\index.tsx`. 

Indeed, none of these files exist:

  * `F:\abc\node_modules\react-native-otp-inputs\lib\index.tsx(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`

  * `F:\abc\node_modules\react-native-otp-inputs\lib\index.tsx\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`

**Comment by dsznajder** [comment] 2019-04-25 09:05
@Abhishekgarg727 closing in favour of #18. Let's keep a track of this here. 

I could not reproduce this one by my self. Send a reproduction in the mentioned issue.

**Closed by dsznajder** 2019-04-25 09:05 UTC

**Comment by Abhishekgarg727** [comment] 2019-04-25 09:06
can you upload your example working code project

**Comment by dsznajder** [comment] 2019-04-25 09:19
@Abhishekgarg727 I've uploaded in mentioned issue

**Comment by Abhishekgarg727** [comment] 2019-04-25 14:02
@dsznajder  i looking forward to fix this issue so i created sample project using react-native-cli and reproduce this issue , here is my git repo of source code https://github.com/Abhishekgarg727/react-native-otp-inputs-error

**Comment by dsznajder** [comment] 2019-04-26 10:33
@Abhishekgarg727 Ok, as I see, this will be related to react-native version. Today I will check which version is correct to use newest version. Please downgrade to 2.0.0. I will deprecate the newest one and create v3.0.0 as it's kinda breaking change.

**Comment by Abhishekgarg727** [comment] 2019-04-26 10:38
@dsznajder  i did not test 2.0.0 version yet, let me compile code again to see that problem persists or not. i  also want to know, is this count as contribution ?

**Comment by Abhishekgarg727** [comment] 2019-04-26 10:55
> @Abhishekgarg727 Ok, as I see, this will be related to react-native version. Today I will check which version is correct to use newest version. Please downgrade to 2.0.0. I will deprecate the newest one and create v3.0.0 as it's kinda breaking change.

i tested version 2.0.0 same problem persists
